### ISSUE TITLE
Error when booting client

### ISSUE THREAD

**Issue by larsvu** [LatvianModder/EMC_Condenser#6]
Crash-Log

Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: com/pahimar/ee3/recipe/RecipesAludel
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:695)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: com/pahimar/ee3/recipe/RecipesAludel
	at latmod.emcc.EMCCRecipes.addInfusing(EMCCRecipes.java:13)
	at latmod.emcc.item.ItemMaterialsEMCC.loadRecipes(ItemMaterialsEMCC.java:66)
	at latmod.core.LMMod.loadRecipes(LMMod.java:110)
	at latmod.emcc.EMCC.postInit(EMCC.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:694)
	... 10 more
Caused by: java.lang.ClassNotFoundException: com.pahimar.ee3.recipe.RecipesAludel
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 40 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 42 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 332886904 bytes (317 MB) / 1025507328 bytes (978 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048m -XX:MaxPermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 Optifine OptiFine_1.7.10_HD_U_B4 44 mods loaded, 44 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	FML{7.10.85.1291} [Forge Mod Loader] (modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Forge{10.13.2.1291} [Minecraft Forge] (modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NotEnoughItems{1.0.3.74} [Not Enough Items] (Not-Enough-Items-1.7.10 (1).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	securitycraft{v1.7.3} [SecurityCraft] ([1.7.10] SecurityCraft 1.7.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ArmorStatusHUD{1.28} [ArmorStatusHUD] ([1.7.10]ArmorStatusHUD-client-1.28.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	IC2{2.2.657-experimental} [IndustrialCraft 2] (Industrial-Craft-2-Mod-Experimental-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	AdvancedMachines{1.0.9} [IC2 Advanced Machines Addon] (Advanced-Machines-Addon-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (Advanced-Solar-Panels-Addon-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	asielib{0.2.7} [asielib] (AsieLib-1.7.10.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Backpack{2.0.1} [Backpack] (Backpacks-Mod.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Core{6.2.6} [BuildCraft] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Forestry{3.4.0.7} [Forestry for Minecraft] (forestry_1.7.10-3.4.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BinnieCore{2.0-pre7} [Binnie Core] (binnie-mods-2.0-pre7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Botany{2.0-pre7} [Botany] (binnie-mods-2.0-pre7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ExtraBees{2.0-pre7} [Extra Bees] (binnie-mods-2.0-pre7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ExtraTrees{2.0-pre7} [Extra Trees] (binnie-mods-2.0-pre7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Genetics{2.0-pre7} [Genetics] (binnie-mods-2.0-pre7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Transport{6.2.6} [BC Transport] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Silicon{6.2.6} [BC Silicon] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Builders{6.2.6} [BC Builders] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Energy{6.2.6} [BC Energy] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Factory{6.2.6} [BC Factory] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	EE3{0.2.434} [Equivalent Exchange 3] (EquivalentExchange3-1.7.10-0.2.434.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	LatCoreMC{1.6.7} [LatCoreMC] (LatCoreMC-1.7.10-1.6.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	EMC_Condenser{1.6.7} [EMC Condenser Mod] (EMC_Condenser-1.7.10-1.6.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Errored
	EnderStorage{1.4.5.27} [EnderStorage] (EnderStorage-1.7.10-1.4.5.27-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	flansmod{4.9.0} [Flan's Mod] (Flans Mod-1.7.10-4.9.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (Inventory-Tweaks-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	IronChest{6.0.62.742} [Iron Chest] (Iron-Chests-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	LatBlocks{1.6.7} [LatBlocks] (LatBlocks-1.7.10-1.6.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Railcraft{9.5.0.0} [Railcraft] (Railcraft_1.7.10-9.5.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ReiMinimap{1.7.10} [Rei's Minimap] (Reis-Minimap-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	RopesPlus{1.6.3} [Ropes+] (RopePlus-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.409.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	statues{2.1.3} [Statues] (Statues-Mod-1.7.10.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ForgeMultipart{1.1.0.309} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	McMultipart{1.1.0.309} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ForgeMicroblock{1.1.0.309} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Optifine
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.

**Comment by LatvianModder** [comment]
Try disabling all infuser recipes in config/latmod/EMC_Condenser.cfg until next version

**Comment by larsvu** [comment]
Does that effect the mod?

**Comment by LatvianModder** [comment]
Only recipes. Should..

**Comment by LatvianModder** [comment]
Wil be fixed in 1.7.8 :p

**Comment by larsvu** [comment]
And when do you release 1.7.8?

**Comment by LatvianModder** [comment]
As soon as possible, this weekend, prolly, there are still few things to fix in all mods together

**Comment by LatvianModder** [comment]
The 1.7.8 EMCC release won't require EE3, as it will have its own EMC system, but it will use EE3's DynEMC if EE3 is installed

**Comment by larsvu** [comment]
I also have an error when booting LatCore in my cauldron server. I pasted the crash file on the LatCoreMC issue section

**Comment by LatvianModder** [comment]
Ah finally figured out, what really happens with this recipe thing, will definetly be fixed now. Turns out Pahimar renamed one file and I was using an older version xP
